management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: reva2111
    url: jdbc:postgresql://pet-app.cziwys5p2mwa.us-east-2.rds.amazonaws.com:5432/postgres?currentSchema=pet_app
    username: postgres
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      platform: postgres
