spring:
  datasource:
    password: ${PA_PASS}
    url: ${PA_URL}
    username: ${PA_USER}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: '*'
